using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Runtime.CompilerServices;

namespace EstateMaster.Server.Adaptor.Helpers.Types
{
    [CompilerGenerated]
    [DebuggerNonUserCode]
    public class MimeTypes
    {
        public static Dictionary<string, string> TypeMap()
        {
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "3g2", "video/3gpp2" },
                { "3gp", "video/3gpp" },
                { "7z", "application/x-7z-compressed" },
                { "accdb", "application/msaccess" },
                { "aif", "audio/x-aiff" },
                { "aifc", "audio/x-aiff" },
                { "aiff", "audio/x-aiff" },
                { "apk", "application/vnd.android.package-archive" },
                { "app", "application/octet-stream" },
                { "asf", "video/x-ms-asf" },
                { "asp", "text/plain" },
                { "aspx", "text/plain" },
                { "avi", "video/x-msvideo" },
                { "b", "text/plain" },
                { "bak", "application/octet-stream" },
                { "bat", "application/x-msdownload" },
                { "bin", "application/octet-stream" },
                { "bmp", "image/bmp" },
                { "c", "text/x-c" },
                { "cab", "application/vnd.ms-cab-compressed" },
                { "cbr", "application/x-cbr" },
                { "cer", "application/pkix-cert" },
                { "cgi", "application/octet-stream" },
                { "class", "application/java-vm" },
                { "com", "application/x-msdownload" },
                { "cpl", "application/octet-stream" },
                { "cpp", "text/x-c" },
                { "cs", "application/octet-stream" },
                { "csr", "application/octet-stream" },
                { "css", "text/css" },
                { "csv", "text/csv" },
                { "cue", "application/x-cue" },
                { "cur", "application/octet-stream" },
                { "dat", "application/octet-stream" },
                { "db", "application/octet-stream" },
                { "dbf", "application/octet-stream" },
                { "dcr", "application/x-director" },
                { "dds", "image/x-dds" },
                { "deb", "application/x-debian-package" },
                { "deskthemepack", "application/octet-stream" },
                { "dem", "application/octet-stream" },
                { "dll", "application/octet-stream" },
                { "dmg", "application/x-apple-diskimage" },
                { "dmp", "application/vnd.tcpdump.pcap" },
                { "doc", "application/msword" },
                { "docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
                { "drv", "application/octet-stream" },
                { "dtd", "application/xml-dtd" },
                { "dwg", "image/vnd.dwg" },
                { "dxf", "image/vnd.dxf" },
                { "exe", "application/octet-stream" },
                { "fla", "application/octet-stream" },
                { "flv", "video/x-flv" },
                { "fon", "application/octet-stream" },
                { "gam", "application/x-tads" },
                { "ged", "application/octet-stream" },
                { "gif", "image/gif" },
                { "gz", "application/x-gz" },
                { "h", "text/x-c" },
                { "htm", "text/html" },
                { "html", "text/html" },
                { "icns", "application/octet-stream" },
                { "ico", "image/x-icon" },
                { "indd", "application/octet-stream" },
                { "iso", "application/x-iso9660-image" },
                { "jar", "application/java-archive" },
                { "java", "text/x-java-source" },
                { "jpg", "image/jpeg" },
                { "js", "application/javascript" },
                { "jsp", "application/jsp" },
                { "key", "application/octet-stream" },
                { "keychain", "application/octet-stream" },
                { "lnk", "application/x-ms-shortcut" },
                { "log", "text/plain" },
                { "lua", "application/octet-stream" },
                { "m3u", "audio/x-mpegurl" },
                { "m3u8", "application/vnd.apple.mpegurl" },
                { "m4a", "audio/mp4" },
                { "m4u", "video/vnd.mpegurl" },
                { "m4v", "video/x-m4v" },
                { "m", "application/matlab-m" },
                { "mdb", "application/x-msaccess" },
                { "mdf", "application/octet-stream" },
                { "mid", "audio/midi" },
                { "midi", "audio/midi" },
                { "mov", "video/quicktime" },
                { "mp3", "audio/mpeg" },
                { "mp4", "video/mp4" },
                { "mpa", "audio/mpeg" },
                { "mpg", "video/mpeg" },
                { "msg", "application/x-msg" },
                { "nes", "application/octet-stream" },
                { "odt", "application/vnd.oasis.opendocument.text" },
                { "otf", "font/otf" },
                { "pages", "application/x-iwork-pages-sffpages" },
                { "pct", "image/x-pict" },
                { "pdb", "application/vnd.palm" },
                { "pdf", "application/pdf" },
                { "php", "application/x-httpd-php" },
                { "pkg", "application/octet-stream" },
                { "pl", "application/x-perl" },
                { "png", "image/png" },
                { "pps", "application/vnd.ms-powerpoint" },
                { "ppt", "application/vnd.ms-powerpoint" },
                { "pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
                { "psd", "image/vnd.adobe.photoshop" },
                { "pspimage", "application/octet-stream" },
                { "py", "application/x-perl" },
                { "rar", "application/x-rar-compressed" },
                { "rm", "application/vnd.rn-realmedia" },
                { "rom", "application/octet-stream" },
                { "rpm", "application/octet-stream" },
                { "rss", "application/rss+xml" },
                { "rtf", "application/rtf" },
                { "sav", "application/octet-stream" },
                { "sdf", "application/octet-stream" },
                { "sh", "application/x-sh" },
                { "sitx", "application/x-stuffitx" },
                { "sln", "application/octet-stream" },
                { "sql", "application/x-sql" },
                { "srt", "application/x-subrip" },
                { "sys", "application/octet-stream" },
                { "swf", "application/x-shockwave-flash" },
                { "swift", "application/octet-stream" },
                { "tar", "application/x-tar" },
                { "tar.gz", "application/tar+gzip" },
                { "tax2016", "application/octet-stream" },
                { "tax2017", "application/octet-stream" },
                { "tex", "application/x-tex" },
                { "tga", "image/x-tga" },
                { "thm", "image/x-thm" },
                { "tif", "image/tiff" },
                { "tiff", "image/tiff" },
                { "tmp", "application/octet-stream" },
                { "toast", "application/octet-stream" },
                { "ttf", "font/ttf" },
                { "txt", "text/plain" },
                { "vb", "application/x-vbs" },
                { "vcd", "application/x-cdlink" },
                { "vcf", "text/x-vcard" },
                { "vcxproj", "application/octet-stream" },
                { "vob", "video/x-ms-vob" },
                { "yuv", "application/octet-stream" },
                { "wav", "audio/x-wav" },
                { "wma", "audio/x-ms-wma" },
                { "wmv", "video/x-ms-wmv" },
                { "wpd", "application/vnd.wordperfect" },
                { "wps", "application/vnd.ms-works" },
                { "wsf", "application/octet-stream" },
                { "xcodeproj", "application/octet-stream" },
                { "xhtml", "application/xhtml+xml" },
                { "xlr", "application/vnd.ms-works" },
                { "xls", "application/excel" },
                { "xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
                { "xml", "application/xml" },
                { "zip", "application/zip" },
                { "zipx", "application/x-zip-compressed" },
            };
        }
    }
}
