--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 22.05.2025 23:27:38
-- Server version: 8.4.2
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8mb4';

--
-- Set default database
--
USE estatemaster;

--
-- Drop table `_psmigrations`
--
DROP TABLE IF EXISTS _psmigrations;

--
-- Drop procedure `sp_create_property`
--
DROP PROCEDURE IF EXISTS sp_create_property;

--
-- Drop table `properties`
--
DROP TABLE IF EXISTS properties;

--
-- Drop procedure `sp_create_user`
--
DROP PROCEDURE IF EXISTS sp_create_user;

--
-- Drop procedure `sp_delete_user`
--
DROP PROCEDURE IF EXISTS sp_delete_user;

--
-- Drop procedure `sp_get_auth_user`
--
DROP PROCEDURE IF EXISTS sp_get_auth_user;

--
-- Drop procedure `sp_get_users`
--
DROP PROCEDURE IF EXISTS sp_get_users;

--
-- Drop procedure `sp_get_user_byID`
--
DROP PROCEDURE IF EXISTS sp_get_user_byID;

--
-- Drop procedure `sp_update_user`
--
DROP PROCEDURE IF EXISTS sp_update_user;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `login_sessions`
--
DROP TABLE IF EXISTS login_sessions;

--
-- Drop procedure `sp_db_exception_msg`
--
DROP PROCEDURE IF EXISTS sp_db_exception_msg;

--
-- Drop procedure `sp_doexception`
--
DROP PROCEDURE IF EXISTS sp_doexception;

--
-- Drop table `db_exception_msg`
--
DROP TABLE IF EXISTS db_exception_msg;

--
-- Set default database
--
USE estatemaster;

--
-- Create table `db_exception_msg`
--
CREATE TABLE db_exception_msg (
  msg varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (msg)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'SQL Ã¼zerinden hata mesajlarÄ± dÃ¶ndÃ¼rmek iÃ§in kullanÄ±lan sistem tablosu',
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_doexception`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_doexception (IN $msg text, IN $code varchar(255))
BEGIN
  SET @no_delete_control = 0;
  SET @global_exception = $msg;
  SET @global_exception_code = $code;
  INSERT INTO db_exception_msg (msg)
    VALUES ('DB_EXCEPTION');
  INSERT INTO db_exception_msg (msg)
    VALUES ('DB_EXCEPTION');
END
$$

--
-- Create procedure `sp_db_exception_msg`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_db_exception_msg (IN $msg text, IN $code varchar(255))
BEGIN
  SET @no_delete_control = 0;
  SET @global_exception = $msg;
  SET @global_exception_code = $code;
  INSERT INTO db_exception_msg (msg)
    VALUES ('DB_EXCEPTION');
  INSERT INTO db_exception_msg (msg)
    VALUES ('DB_EXCEPTION');
END
$$

DELIMITER ;

--
-- Create table `login_sessions`
--
CREATE TABLE login_sessions (
  id char(36) NOT NULL DEFAULT '',
  user_id char(36) NOT NULL,
  login_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_type int NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Oturumlar',
ROW_FORMAT = DYNAMIC;

--
-- Create table `users`
--
CREATE TABLE users (
  id char(36) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  created_by varchar(255) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  surname varchar(255) DEFAULT NULL,
  phone varchar(20) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  userType varchar(50) DEFAULT NULL,
  username varchar(50) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  login_date datetime DEFAULT NULL,
  description text DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_update_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_update_user (IN p_id char(36),
IN p_created_at datetime,
IN p_updated_at datetime,
IN p_created_by varchar(255),
IN p_name varchar(255),
IN p_surname varchar(255),
IN p_phone varchar(20),
IN p_state varchar(50),
IN p_userType varchar(50),
IN p_username varchar(50),
IN p_password varchar(255),
IN p_login_date datetime,
IN p_description text,
IN p_email varchar(255))
BEGIN
  START TRANSACTION;

    UPDATE users
    SET created_at = p_created_at,
        updated_at = NOW(),
        created_by = p_created_by,
        name = p_name,
        surname = p_surname,
        phone = p_phone,
        state = p_state,
        userType = p_userType,
        username = p_username,
        password = p_password,
        login_date = p_login_date,
        email = p_email,
        description = p_description
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT created_at, updated_at, created_by, name, surname, phone, state, userType, username, password, 
         login_date
  FROM   users
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `sp_get_user_byID`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_user_byID (IN $id char(36))
BEGIN
  SELECT
    id,
    created_at,
    updated_at,
    created_by,
    name,
    surname,
    phone,
    state,
    userType,
    username,
    password,
    login_date,
    email,
    description
  FROM users
  WHERE id = $id;
END
$$

--
-- Create procedure `sp_get_users`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_users ()
BEGIN
  SELECT
    *
  FROM users;
END
$$

--
-- Create procedure `sp_get_auth_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_auth_user (IN $username varchar(255), IN $password varchar(255))
BEGIN
  DECLARE intUserID char(36) DEFAULT '';
  DECLARE intID char(36);
  SET intID = UUID();

  SELECT
    id INTO intUserID
  FROM users
  WHERE username = $username
  AND password = $password;

  IF IFNULL(intUserID, '') = ''
    OR IFNULL($password, '') = '' THEN
  BEGIN
    CALL sp_db_exception_msg('Authentication failed..!', 'UE-01');
  END;
  ELSE
  BEGIN

    INSERT INTO login_sessions (id, user_id)
      VALUES (intID, intUserID);
    SELECT
      a.id,
      a.created_at,
      a.updated_at,
      a.created_by,
      a.name,
      a.surname,
      a.phone,
      a.state,
      a.userType,
      a.username,
      a.password,
      a.login_date,
      intID AS session_id
    FROM users AS a
    WHERE a.id = intUserID;
  END;
  END IF;

END
$$

--
-- Create procedure `sp_delete_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_delete_user (IN $id char(36))
BEGIN
  DECLARE intControl int DEFAULT 0;

  SELECT
    IFNULL(SUM(1), 0) INTO intControl
  FROM users
  WHERE id = $id;

  IF IFNULL(intControl, 0) = 0 THEN
    CALL sp_doexception('Record not found..!', 'BL-01');
  END IF;

  DELETE
    FROM users
  WHERE id = $id;
END
$$

--
-- Create procedure `sp_create_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_user (IN p_created_at datetime,
IN p_updated_at datetime,
IN p_created_by varchar(255),
IN p_name varchar(255),
IN p_surname varchar(255),
IN p_phone varchar(20),
IN p_state varchar(50),
IN p_userType varchar(50),
IN p_username varchar(50),
IN p_password varchar(255),
IN p_login_date datetime,
IN p_description text,
IN p_email varchar(255))
main_block:
  BEGIN
    DECLARE intID char(36);
    DECLARE userCount int DEFAULT 0;
    SET @oresult = '';

    -- Kullanıcı adı kontrolü
    SELECT
      COUNT(*) INTO userCount
    FROM users
    WHERE username = p_username;
    IF userCount > 0 THEN
      SET @oresult = 'USERNAME_EXISTS';
      SELECT
        @oresult AS oresult;
      ROLLBACK;
      LEAVE main_block;
    END IF;

    SET intID = UUID();
    START TRANSACTION;

      INSERT INTO users (id, created_at, updated_at, created_by, name, surname, phone, state, userType, username, password, login_date, description, email)
        VALUES (intID, NOW(), NOW(), p_created_by, p_name, p_surname, p_phone, p_state, p_userType, p_username, p_password, NOW(), p_description, p_email);

      SET @oresult = intID;
      SELECT
        @oresult AS oresult;
    COMMIT;
  END
  $$

DELIMITER ;

--
-- Create table `properties`
--
CREATE TABLE properties (
  id char(36) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  created_by varchar(255) DEFAULT NULL,
  property_type varchar(255) DEFAULT NULL,
  user_id char(36) DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  description text DEFAULT NULL,
  price double DEFAULT NULL,
  province varchar(255) DEFAULT NULL,
  district varchar(255) DEFAULT NULL,
  square_meters_net double DEFAULT NULL,
  neighborhood varchar(255) DEFAULT NULL,
  estate_status_type varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_create_property`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_property (IN p_created_at datetime,
IN p_updated_at datetime,
IN p_created_by varchar(255),
IN p_property_type varchar(255),
IN p_user_id char(36),
IN p_title varchar(255),
IN p_description text,
IN p_price double(12, 2),
IN p_province varchar(255),
IN p_district varchar(255),
IN p_square_meters_net double(12, 2),
IN p_neighborhood varchar(255),
IN p_estate_status_type varchar(255))
BEGIN
  DECLARE intID char(36);
  SET intID = UUID();
  SET @oresult = '';
  START TRANSACTION;

    INSERT INTO properties (id,
    created_at,
    updated_at,
    created_by,
    property_type,
    user_id,
    title,
    description,
    price,
    province,
    district,
    square_meters_net,
    neighborhood,
    estate_status_type)
      VALUES (intID, NOW(), NOW(), p_created_by, p_property_type, p_user_id, p_title, p_description, p_price, p_province, p_district, p_square_meters_net, p_neighborhood, p_estate_status_type);

    SET @oresult = intID;
    SELECT
      @oresult AS oresult;
  COMMIT;
END
$$

DELIMITER ;

--
-- Create table `_psmigrations`
--
CREATE TABLE _psmigrations (
  id int NOT NULL,
  name varchar(255) NOT NULL,
  executed_at datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

-- Table estatemaster._psmigrations does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
('34cd746e-35ab-11f0-9fb3-e40d36081ab9', '2025-05-20 21:49:49', '2025-05-20 21:49:49', 'cansugoksen', 'Deniz', 'Gökşen', '5449110054', 'Sakarya', 'admin', 'denizgoksen', '123', '2025-05-20 21:49:49', '123', 'knngksn@hotmail.com'),
('763553f7-35a6-11f0-9fb3-e40d36081ab9', '2025-05-20 21:15:51', '2025-05-20 21:15:51', 'cansugoksen', 'Kenan', 'Gökşen', '5449110054', 'Sakarya', 'modaretor', 'knngksn', '123', '2025-05-20 21:15:51', 'test2', 'knngksn@hotmail.com'),
('c78b7881-35aa-11f0-9fb3-e40d36081ab9', '2025-05-20 21:46:45', '2025-05-20 21:46:45', 'cansugoksen', 'Kenan', 'Gökşen', '5449110054', 'Bursa', 'admin', 'knngksn1', '123', '2025-05-20 21:46:45', '123', 'knngksn@hotmail.com'),
('ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2024-12-05 19:21:04', '2025-05-20 22:01:43', 'knngksn', 'Cansu', 'Gökşen Dğiştirildi', '5449110054', 'Sakarya', 'admin', 'cansugoksen', 'Kgksn.0507', '2024-12-05 19:21:04', 'Test', 'knngksn@hotmail.com'),
('f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-11-22 21:52:37', '2025-03-25 08:52:25', 'knngksn', 'Kenan', 'Gökşen', '0532 232 70 54', 'Kırşehir', 'saleperson', 'knngksn', 'Kgksn.0507', '2024-11-22 21:52:37', 'Test Hesabı Silme...!!!!!!!!', 'knngksn@hotmail.com');

-- 
-- Dumping data for table properties
--
INSERT INTO properties VALUES
('5098fccc-35ca-11f0-9fb3-e40d36081ab9', '2025-05-21 01:32:30', '2025-05-21 01:32:30', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asd', 'asd', 123, 'asd', 'asd', 123, 'asd', 'sale'),
('50da7176-35cb-11f0-9fb3-e40d36081ab9', '2025-05-21 01:39:39', '2025-05-21 01:39:39', 'knngksn', 'land', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'Satılı Arsa', '597 metre kare sapanca gölü manzaralı imarlı arsa', 500000, 'Sakarya', 'Serdivan', 597, 'Esentepe Mahallesi', 'sale'),
('6e3bd983-35cc-11f0-9fb3-e40d36081ab9', '2025-05-21 01:47:38', '2025-05-21 01:47:38', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asdasda', 'asdasd', 123123, 'asda', 'asdasd', 123123, 'asdasd', 'sale'),
('7e441ae8-35c9-11f0-9fb3-e40d36081ab9', '2025-05-21 01:26:37', '2025-05-21 01:26:37', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asd', 'asd', 123, 'asd', 'asd', 123, 'asd', 'sale'),
('a806ca04-35cc-11f0-9fb3-e40d36081ab9', '2025-05-21 01:49:15', '2025-05-21 01:49:15', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asdasd', 'asdas', 123, 'asdasd', 'asd', 123123, 'asdasd', 'sale');

-- 
-- Dumping data for table login_sessions
--
INSERT INTO login_sessions VALUES
('000c4d36-6617-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 17:57:24', 0),
('032ee32f-66cc-11ef-b915-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-08-30 15:33:08', 0),
('060e1e42-a8ff-11ef-a0c7-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-22 21:24:34', 0),
('0b9ca9b4-64d7-11ef-b915-b025aa5ee41d', '', '2024-08-28 03:47:04', 0),
('110b594b-6527-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:19:53', 0),
('1afb7e6c-663d-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 22:30:10', 0),
('1f022aed-35ce-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 01:59:44', 0),
('2661ea3f-64de-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:37:56', 0),
('2770e31d-35ce-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 01:59:58', 0),
('27f9902f-6520-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:30:25', 0),
('2b52c208-35cf-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 02:07:14', 0),
('2ccf9536-64da-11ef-b915-b025aa5ee41d', '2', '2024-08-28 04:09:28', 0),
('2dff0b5f-64d2-11ef-b915-b025aa5ee41d', '', '2024-08-28 03:12:14', 0),
('31cd0b6d-663d-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 22:30:48', 0),
('385e50f3-6527-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:20:59', 0),
('3e310b80-b324-11ef-81a0-b025aa5ee41d', '37f720ba-b324-11ef-81a0-b025aa5ee41d', '2024-12-05 19:16:11', 0),
('3ec0127b-654e-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 18:00:20', 0),
('407b8fea-6551-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 18:21:52', 0),
('414eb5d9-6552-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 18:29:02', 0),
('4ac945c3-094a-11f0-bbc1-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-25 10:25:13', 0),
('4b546c03-9326-11ef-b11d-e40d36081ab9', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-10-26 02:10:15', 0),
('4b8ac796-093d-11f0-bbc1-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-03-25 08:52:11', 0),
('4c5bac0d-652a-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:43:01', 0),
('4fe94416-093d-11f0-bbc1-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-03-25 08:52:18', 0),
('505da356-64dc-11ef-b915-b025aa5ee41d', '', '2024-08-28 04:24:47', 0),
('50b3093b-6554-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 18:43:47', 0),
('5109ca39-35a3-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-20 20:53:20', 0),
('520ca422-6521-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:38:45', 0),
('5703f934-093d-11f0-bbc1-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-03-25 08:52:30', 0),
('583b9c00-a902-11ef-a0c7-b025aa5ee41d', '56cc975d-a902-11ef-a0c7-b025aa5ee41d', '2024-11-22 21:48:20', 0),
('59ac18f9-bb1c-11ef-9846-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-15 22:39:50', 0),
('5ae16704-6619-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-29 18:14:15', 0),
('5c8f73a0-6547-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:11:04', 0),
('67589cf5-6522-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:46:30', 0),
('6776ab4d-655c-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:41:41', 0),
('6ba5d91b-6552-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 18:30:13', 0),
('6d1b588e-64de-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:39:54', 0),
('7265720a-66c0-11ef-b915-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-08-30 14:10:21', 0),
('73af1be9-70fa-11ef-b915-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-09-12 14:30:45', 0),
('76ea982b-35cd-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 01:55:02', 0),
('78999b18-6551-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 18:23:26', 0),
('7d840da2-35a4-11f0-9fb3-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-05-20 21:01:44', 0),
('7d883d5b-6526-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:15:46', 0),
('7f6c5c6d-663f-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 22:47:17', 0),
('810a6fb5-64d9-11ef-b915-b025aa5ee41d', '', '2024-08-28 04:04:40', 0),
('89c36a3f-64dd-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:33:33', 0),
('8b9da01c-6547-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:12:23', 0),
('8c679ad5-64e0-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:55:06', 0),
('8e2d4ed1-2d97-11f0-9159-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-05-10 15:08:59', 0),
('9024cfaa-64db-11ef-b915-b025aa5ee41d', '', '2024-08-28 04:19:25', 0),
('96972082-6558-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:14:22', 0),
('9945d0a3-b324-11ef-81a0-b025aa5ee41d', '92aab838-b324-11ef-81a0-b025aa5ee41d', '2024-12-05 19:18:44', 0),
('99577ea4-6547-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:12:46', 0),
('9a135df8-6619-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 18:16:01', 0),
('9c8c78aa-665d-11ef-b915-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-08-30 02:22:51', 0),
('9e373d7e-6558-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:14:35', 0),
('a0253179-6520-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:33:47', 0),
('a486c668-665d-11ef-b915-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-08-30 02:23:05', 0),
('a7e224b3-6529-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:38:25', 0),
('a82b7b54-6558-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:14:52', 0),
('a928189a-0939-11f0-bbc1-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-25 08:26:10', 0),
('af58b3a0-35cd-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 01:56:37', 0),
('b5a369b5-6558-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:15:15', 0),
('b5fd87bd-093b-11f0-bbc1-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-03-25 08:40:50', 0),
('b923b93c-bde4-11ef-9846-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-19 11:39:12', 0),
('b9bd7564-a8fe-11ef-a0c7-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-22 21:22:26', 0),
('ba10d0da-b46c-11ef-81a0-b025aa5ee41d', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-07 10:27:34', 0),
('be298d24-094f-11f0-bbc1-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-25 11:04:14', 0),
('c16f1594-35ac-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-20 22:00:54', 0),
('c1fb46b5-a8fc-11ef-a0c7-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-22 21:08:21', 0),
('c53a8aa4-05a6-11f0-bbc1-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-20 19:17:08', 0),
('c561320e-6556-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:01:22', 0),
('c7eac9be-b323-11ef-81a0-b025aa5ee41d', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-05 19:12:53', 0),
('cad7700b-654a-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:35:37', 0),
('cd32eeba-3749-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-22 23:17:36', 0),
('cf4e03cb-05a9-11f0-bbc1-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-20 19:38:53', 0),
('d0fc46a9-651f-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:27:59', 0),
('d15718a7-2d03-11f0-9159-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-09 21:31:26', 0),
('d36743f3-094e-11f0-bbc1-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-25 10:57:40', 0),
('d6a6970f-6547-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:14:29', 0),
('d746c703-b324-11ef-81a0-b025aa5ee41d', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-05 19:20:28', 0),
('da823d5c-b324-11ef-81a0-b025aa5ee41d', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-05 19:20:33', 0),
('e0c4965f-6547-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:14:45', 0),
('e57c6564-6558-11ef-b915-b025aa5ee41d', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:16:35', 0),
('e5f5a9ce-64db-11ef-b915-b025aa5ee41d', '', '2024-08-28 04:21:49', 0),
('e8fbc85a-64dd-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:36:13', 0),
('ea4b4527-a8fc-11ef-a0c7-b025aa5ee41d', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-22 21:09:28', 0),
('eaa4def3-9b93-11ef-b12d-e40d36081ab9', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-05 19:35:07', 0),
('ee208c9d-0dad-11f0-bbc1-e40d36081ab9', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-31 00:28:32', 0),
('f06e7e32-b324-11ef-81a0-b025aa5ee41d', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2024-12-05 19:21:10', 0),
('f5c23789-64dc-11ef-b915-b025aa5ee41d', '6b5a2e0f-9c7a-4a1b-8e5d-3e8a1f9b5d6c', '2024-08-28 04:29:25', 0),
('f67827ea-6528-11ef-b915-b025aa5ee41d', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:33:27', 0),
('f6b65ff7-a902-11ef-a0c7-b025aa5ee41d', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-11-22 21:52:46', 0),
('fa903854-35ce-11f0-9fb3-e40d36081ab9', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 02:05:53', 0);

-- 
-- Dumping data for table db_exception_msg
--
INSERT INTO db_exception_msg VALUES
('DB_EXCEPTION');

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;