--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30.08.2025 02:58:40
-- Server version: 8.4.2
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8mb4';

--
-- Set default database
--
USE estatemaster;

--
-- Drop table `company_limits`
--
DROP TABLE IF EXISTS company_limits;

--
-- Drop table `_psmigrations`
--
DROP TABLE IF EXISTS _psmigrations;

--
-- Drop procedure `sp_create_customer`
--
DROP PROCEDURE IF EXISTS sp_create_customer;

--
-- Drop procedure `sp_get_customers`
--
DROP PROCEDURE IF EXISTS sp_get_customers;

--
-- Drop procedure `sp_get_customer_by_id`
--
DROP PROCEDURE IF EXISTS sp_get_customer_by_id;

--
-- Drop procedure `sp_toggle_customer_active_state`
--
DROP PROCEDURE IF EXISTS sp_toggle_customer_active_state;

--
-- Drop procedure `sp_update_customer`
--
DROP PROCEDURE IF EXISTS sp_update_customer;

--
-- Drop table `customers`
--
DROP TABLE IF EXISTS customers;

--
-- Drop procedure `sp_create_property`
--
DROP PROCEDURE IF EXISTS sp_create_property;

--
-- Drop procedure `sp_get_properties`
--
DROP PROCEDURE IF EXISTS sp_get_properties;

--
-- Drop table `properties`
--
DROP TABLE IF EXISTS properties;

--
-- Drop procedure `sp_create_user`
--
DROP PROCEDURE IF EXISTS sp_create_user;

--
-- Drop procedure `sp_delete_user`
--
DROP PROCEDURE IF EXISTS sp_delete_user;

--
-- Drop procedure `sp_get_auth_user`
--
DROP PROCEDURE IF EXISTS sp_get_auth_user;

--
-- Drop procedure `sp_get_users`
--
DROP PROCEDURE IF EXISTS sp_get_users;

--
-- Drop procedure `sp_get_user_byID`
--
DROP PROCEDURE IF EXISTS sp_get_user_byID;

--
-- Drop procedure `sp_load_session`
--
DROP PROCEDURE IF EXISTS sp_load_session;

--
-- Drop procedure `sp_update_user`
--
DROP PROCEDURE IF EXISTS sp_update_user;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `login_sessions`
--
DROP TABLE IF EXISTS login_sessions;

--
-- Drop table `companies`
--
DROP TABLE IF EXISTS companies;

--
-- Drop procedure `sp_db_exception_msg`
--
DROP PROCEDURE IF EXISTS sp_db_exception_msg;

--
-- Drop procedure `sp_doexception`
--
DROP PROCEDURE IF EXISTS sp_doexception;

--
-- Drop table `db_exception_msg`
--
DROP TABLE IF EXISTS db_exception_msg;

--
-- Set default database
--
USE estatemaster;

--
-- Create table `db_exception_msg`
--
CREATE TABLE db_exception_msg (
  id int UNSIGNED NOT NULL,
  session_id char(36) DEFAULT NULL COMMENT 'Hata oluşan session_id',
  user_id char(36) DEFAULT NULL COMMENT 'Hata tetikleyen kullanıcı',
  msg text NOT NULL COMMENT 'Hata mesajı (Türkçe)',
  code varchar(255) DEFAULT NULL COMMENT 'Hata kodu',
  level varchar(20) DEFAULT 'ERROR' COMMENT 'Hata seviyesİ: INFO, WARNING, ERROR, FATAL',
  created_at datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Kayıt zamanı',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 19,
AVG_ROW_LENGTH = 963,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Sistem üzerinden oluşan hataları loglamak için kullanılan tablo',
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_doexception`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_doexception (IN p_message text,
IN p_code varchar(255),
IN p_session_id char(36),
IN p_user_id char(36),
IN p_level varchar(20))
BEGIN
  -- Set global variables for reference (optional)
  SET @global_exception_message = p_message;
  SET @global_exception_code = p_code;

  -- Insert log entry into exception table
  INSERT INTO db_exception_msg (session_id,
  user_id,
  msg,
  code,
  level,
  created_at)
    VALUES (p_session_id, p_user_id, p_message, p_code, IFNULL(p_level, 'ERROR'), NOW());

  -- Optional: Return user-facing message
  SELECT
    CONCAT('An error occurred: ', p_message) AS error_message,
    p_code AS error_code,
    IFNULL(p_level, 'ERROR') AS level;
END
$$

--
-- Create procedure `sp_db_exception_msg`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_db_exception_msg (IN $msg text, IN $code varchar(255))
BEGIN
  SET @no_delete_control = 0;
  SET @global_exception = $msg;
  SET @global_exception_code = $code;
  INSERT INTO db_exception_msg (msg)
    VALUES ('DB_EXCEPTION');
  INSERT INTO db_exception_msg (msg)
    VALUES ('DB_EXCEPTION');
END
$$

DELIMITER ;

--
-- Create table `companies`
--
CREATE TABLE companies (
  id char(36) NOT NULL COMMENT 'Şirketin benzersiz UUID değeri',
  company_code varchar(12) NOT NULL COMMENT 'Onboarding ve erişim kodu',
  name varchar(100) NOT NULL COMMENT 'Şirket adı',
  company_email varchar(120) DEFAULT NULL COMMENT 'Şirket iletişim e-posta adresi',
  domain varchar(100) DEFAULT NULL COMMENT 'Opsiyonel domain bilgisi',
  is_active tinyint(1) DEFAULT 1 COMMENT 'Şirketin sistemde aktiflik durumu',
  created_at datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Oluşturulma zamanı',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Sistemdeki şirket bilgilerini tutan ana tablo',
ROW_FORMAT = DYNAMIC;

--
-- Create index `company_code` on table `companies`
--
ALTER TABLE companies
ADD UNIQUE INDEX company_code (company_code);

--
-- Create table `login_sessions`
--
CREATE TABLE login_sessions (
  id char(36) NOT NULL DEFAULT '',
  company_id char(36) NOT NULL,
  user_id char(36) NOT NULL,
  login_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_type int NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Oturumlar',
ROW_FORMAT = DYNAMIC;

--
-- Create table `users`
--
CREATE TABLE users (
  id char(36) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  created_by varchar(255) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  surname varchar(255) DEFAULT NULL,
  phone varchar(20) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  userType varchar(50) DEFAULT NULL,
  username varchar(50) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  login_date datetime DEFAULT NULL,
  description text DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  company_id char(36) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_update_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_update_user (IN p_id char(36),
IN p_created_at datetime,
IN p_updated_at datetime,
IN p_created_by varchar(255),
IN p_name varchar(255),
IN p_surname varchar(255),
IN p_phone varchar(20),
IN p_state varchar(50),
IN p_userType varchar(50),
IN p_username varchar(50),
IN p_password varchar(255),
IN p_login_date datetime,
IN p_description text,
IN p_email varchar(255))
BEGIN
  START TRANSACTION;

    UPDATE users
    SET created_at = p_created_at,
        updated_at = NOW(),
        created_by = p_created_by,
        name = p_name,
        surname = p_surname,
        phone = p_phone,
        state = p_state,
        userType = p_userType,
        username = p_username,
        password = p_password,
        login_date = p_login_date,
        email = p_email,
        description = p_description
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT created_at, updated_at, created_by, name, surname, phone, state, userType, username, password, 
         login_date
  FROM   users
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `sp_load_session`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_load_session (IN p_session_id char(36))
BEGIN
  SET @GlobalUserId = '';
  SET @GlobalCompanyId = '';
  SET @GlobalUserRole = '';
  SET @GlobalCompanyCode = '';

  IF IFNULL(p_session_id, '') = '' THEN
    CALL sp_doexception('Sistem Hatası: session_id boş olamaz.',
    'AUTH-01',
    p_session_id,
    '',
    'ERROR');
    CALL sp_load_session;
  END IF;

  SELECT
    s.user_id,
    s.company_id,
    u.userType,
    c.company_code INTO @GlobalUserId,
  @GlobalCompanyId,
  @GlobalUserRole,
  @GlobalCompanyCode
  FROM login_sessions s
    INNER JOIN users u
      ON u.id = s.user_id
    INNER JOIN companies c
      ON c.id = s.company_id
  WHERE s.id = p_session_id;

  IF IFNULL(@GlobalUserId, '') = '' THEN
    CALL sp_doexception('Sistem Hatası: oturum bulunamadı.',
    'AUTH-02',
    p_session_id,
    '',
    'ERROR');
  END IF;

  SELECT
    @GlobalUserId AS user_id,
    @GlobalCompanyId AS company_id,
    @GlobalUserRole AS user_type,
    @GlobalCompanyCode AS company_code;
END
$$

--
-- Create procedure `sp_get_user_byID`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_user_byID (IN $id char(36))
BEGIN
  SELECT
    id,
    created_at,
    updated_at,
    created_by,
    name,
    surname,
    phone,
    state,
    userType,
    username,
    password,
    login_date,
    email,
    description
  FROM users
  WHERE id = $id;
END
$$

--
-- Create procedure `sp_get_users`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_users ()
BEGIN
  SELECT
    *
  FROM users;
END
$$

--
-- Create procedure `sp_get_auth_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_auth_user (IN $username varchar(255),
IN $password varchar(255))
BEGIN
  DECLARE intUserID char(36) DEFAULT '';
  DECLARE intID char(36);
  DECLARE strCompanyID char(36) DEFAULT '';

  SET intID = UUID();

  -- Kullanıcı doğrulama + company_id (UUID) alınması
  SELECT
    id,
    company_id INTO intUserID, strCompanyID
  FROM estatemaster.users
  WHERE username = $username
  AND password = $password;

  -- Kullanıcı bulunamadıysa
  IF IFNULL(intUserID, '') = '' THEN
    CALL sp_db_exception_msg('Authentication failed..!', 'UE-01');
  ELSE
    -- login_sessions tablosuna UUID’li company_id ile kayıt
    INSERT INTO estatemaster.login_sessions (id, user_id, user_type, company_id, login_date)
      VALUES (intID, intUserID, 1, strCompanyID, NOW());

    -- Kullanıcı bilgilerini döndür
    SELECT
      a.id,
      a.created_at,
      a.updated_at,
      a.created_by,
      a.name,
      a.surname,
      a.phone,
      a.state,
      a.userType,
      a.username,
      a.password,
      a.login_date,
      a.company_id,
      intID AS session_id
    FROM estatemaster.users AS a
    WHERE a.id = intUserID;
  END IF;
END
$$

--
-- Create procedure `sp_delete_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_delete_user (IN $id char(36))
BEGIN
  DECLARE intControl int DEFAULT 0;

  SELECT
    IFNULL(SUM(1), 0) INTO intControl
  FROM users
  WHERE id = $id;

  IF IFNULL(intControl, 0) = 0 THEN
    CALL sp_doexception('Record not found..!', 'BL-01');
  END IF;

  DELETE
    FROM users
  WHERE id = $id;
END
$$

--
-- Create procedure `sp_create_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_user (IN p_created_at datetime,
IN p_updated_at datetime,
IN p_created_by varchar(255),
IN p_name varchar(255),
IN p_surname varchar(255),
IN p_phone varchar(20),
IN p_state varchar(50),
IN p_userType varchar(50),
IN p_username varchar(50),
IN p_password varchar(255),
IN p_login_date datetime,
IN p_description text,
IN p_email varchar(255))
main_block:
  BEGIN
    DECLARE intID char(36);
    DECLARE userCount int DEFAULT 0;
    SET @oresult = '';

    -- Kullanıcı adı kontrolü
    SELECT
      COUNT(*) INTO userCount
    FROM users
    WHERE username = p_username;
    IF userCount > 0 THEN
      SET @oresult = 'USERNAME_EXISTS';
      SELECT
        @oresult AS oresult;
      ROLLBACK;
      LEAVE main_block;
    END IF;

    SET intID = UUID();
    START TRANSACTION;

      INSERT INTO users (id, created_at, updated_at, created_by, name, surname, phone, state, userType, username, password, login_date, description, email)
        VALUES (intID, NOW(), NOW(), p_created_by, p_name, p_surname, p_phone, p_state, p_userType, p_username, p_password, NOW(), p_description, p_email);

      SET @oresult = intID;
      SELECT
        @oresult AS oresult;
    COMMIT;
  END
  $$

DELIMITER ;

--
-- Create table `properties`
--
CREATE TABLE properties (
  id char(36) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  created_by varchar(255) DEFAULT NULL,
  property_type varchar(255) DEFAULT NULL,
  user_id char(36) DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  description text DEFAULT NULL,
  price double DEFAULT NULL,
  province varchar(255) DEFAULT NULL,
  district varchar(255) DEFAULT NULL,
  square_meters_net double DEFAULT NULL,
  neighborhood varchar(255) DEFAULT NULL,
  estate_status_type varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_get_properties`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_properties ()
BEGIN
  SELECT
    *
  FROM properties;
END
$$

--
-- Create procedure `sp_create_property`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_property (IN p_created_at datetime,
IN p_updated_at datetime,
IN p_created_by varchar(255),
IN p_property_type varchar(255),
IN p_user_id char(36),
IN p_title varchar(255),
IN p_description text,
IN p_price double(12, 2),
IN p_province varchar(255),
IN p_district varchar(255),
IN p_square_meters_net double(12, 2),
IN p_neighborhood varchar(255),
IN p_estate_status_type varchar(255))
BEGIN
  DECLARE intID char(36);
  SET intID = UUID();
  SET @oresult = '';
  START TRANSACTION;

    INSERT INTO properties (id,
    created_at,
    updated_at,
    created_by,
    property_type,
    user_id,
    title,
    description,
    price,
    province,
    district,
    square_meters_net,
    neighborhood,
    estate_status_type)
      VALUES (intID, NOW(), NOW(), p_created_by, p_property_type, p_user_id, p_title, p_description, p_price, p_province, p_district, p_square_meters_net, p_neighborhood, p_estate_status_type);

    SET @oresult = intID;
    SELECT
      @oresult AS oresult;
  COMMIT;
END
$$

DELIMITER ;

--
-- Create table `customers`
--
CREATE TABLE customers (
  id char(36) NOT NULL COMMENT 'Müşteri ID (benzersiz UUID formatı)',
  company_id char(36) NOT NULL COMMENT 'Şirket ID ',
  created_at datetime DEFAULT NULL COMMENT 'Oluşturulma tarihi',
  updated_at datetime DEFAULT NULL COMMENT 'Son güncelleme tarihi',
  created_by varchar(255) DEFAULT NULL COMMENT 'Kaydı oluşturan kullanıcı ID veya adı',
  customer_type varchar(255) DEFAULT NULL COMMENT 'Müşteri tipi (Potansiyel, Aktif, Eski)',
  assigned_user_id char(36) DEFAULT NULL COMMENT 'Danışman ID (ilgili kullanıcı)',
  first_name varchar(255) DEFAULT NULL COMMENT 'Adı',
  last_name varchar(255) DEFAULT NULL COMMENT 'Soyadı',
  email varchar(255) DEFAULT NULL COMMENT 'E-posta adresi',
  phone varchar(25) DEFAULT NULL COMMENT 'Telefon numarası',
  birth_date date DEFAULT NULL COMMENT 'Doğum tarihi',
  gender varchar(10) DEFAULT NULL COMMENT 'Cinsiyet',
  budget_min double DEFAULT NULL COMMENT 'Bütçe alt sınırı',
  budget_max double DEFAULT NULL COMMENT 'Bütçe üst sınırı',
  preferred_province varchar(255) DEFAULT NULL COMMENT 'Tercih edilen il',
  preferred_district varchar(255) DEFAULT NULL COMMENT 'Tercih edilen ilçe',
  preferred_neighborhood varchar(255) DEFAULT NULL COMMENT 'Tercih edilen mahalle',
  preferred_square_meters double DEFAULT NULL COMMENT 'Tercih edilen net m²',
  preferred_room_count varchar(50) DEFAULT NULL COMMENT 'Tercih edilen oda sayısı (ör. 2+1)',
  amenities text DEFAULT NULL COMMENT 'Sosyal olanaklar (ör. havuz, otopark)',
  facade varchar(100) DEFAULT NULL COMMENT 'Tercih edilen cephe (ör. güney)',
  source varchar(100) DEFAULT NULL COMMENT 'Müşteri kaynağı (ör. Instagram, tavsiye)',
  last_interaction datetime DEFAULT NULL COMMENT 'Son görüşme / etkileşim tarihi',
  notes text DEFAULT NULL COMMENT 'Açıklamalar, notlar',
  is_active tinyint(1) DEFAULT 1 COMMENT 'Aktiflik durumu (true: aktif, false: pasif)',
  updated_by varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_update_customer`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_update_customer (IN p_id char(36),
IN p_session_id char(36),
IN p_company_id char(36),
IN p_customer_type varchar(255),
IN p_assigned_user_id char(36),
IN p_first_name varchar(255),
IN p_last_name varchar(255),
IN p_email varchar(255),
IN p_phone varchar(25),
IN p_birth_date date,
IN p_gender varchar(10),
IN p_budget_min double,
IN p_budget_max double,
IN p_preferred_province varchar(255),
IN p_preferred_district varchar(255),
IN p_preferred_neighborhood varchar(255),
IN p_preferred_square_meters double,
IN p_preferred_room_count varchar(50),
IN p_amenities text,
IN p_facade varchar(100),
IN p_source varchar(100),
IN p_last_interaction datetime,
IN p_notes text,
IN p_updated_by char(36))
main_block:
  BEGIN
    DECLARE actualCompany char(36);
    DECLARE actualUser char(36);
    SET @oresult = '';
    SET @omessage = '';

    -- Oturum doğrulama
    CALL sp_load_session(p_session_id);

    SELECT
      @GlobalCompanyId INTO actualCompany;
    SELECT
      @GlobalUserId INTO actualUser;

    -- Tenant ve kullanıcı doğrulama
    IF actualCompany != p_company_id THEN
      CALL sp_db_exception_msg('Tenant geçersiz veya eşleşmiyor.', 'UE-02');
      LEAVE main_block;
    END IF;

    --  Kayıt kontrolü
    IF NOT EXISTS (SELECT
          1
        FROM estatemaster.customers
        WHERE id = p_id
        AND company_id = p_company_id) THEN
      SET @oresult = 'NOT_FOUND';
      SET @omessage = 'Müşteri kaydı bulunamadı.';
      SELECT
        @oresult AS oresult,
        @omessage AS message;
      LEAVE main_block;
    END IF;

    -- Güncelleme işlemi
    UPDATE estatemaster.customers
    SET customer_type = p_customer_type,
        assigned_user_id = p_assigned_user_id,
        first_name = p_first_name,
        last_name = p_last_name,
        email = p_email,
        phone = p_phone,
        birth_date = p_birth_date,
        gender = p_gender,
        budget_min = p_budget_min,
        budget_max = p_budget_max,
        preferred_province = p_preferred_province,
        preferred_district = p_preferred_district,
        preferred_neighborhood = p_preferred_neighborhood,
        preferred_square_meters = p_preferred_square_meters,
        preferred_room_count = p_preferred_room_count,
        amenities = p_amenities,
        facade = p_facade,
        source = p_source,
        last_interaction = p_last_interaction,
        notes = p_notes,
        updated_by = p_updated_by,
        updated_at = NOW()
    WHERE id = p_id
    AND company_id = p_company_id;

    -- Başarılı cevap
    SET @oresult = 'UPDATED';
    SET @omessage = 'Müşteri bilgileri başarıyla güncellendi.';
    SELECT
      @oresult AS oresult,
      @omessage AS message;
  END
  $$

--
-- Create procedure `sp_toggle_customer_active_state`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_toggle_customer_active_state (IN p_id char(36))
main_block:
  BEGIN
    DECLARE current_state boolean DEFAULT TRUE;
    SET @oresult = '';

    -- Kayıt var mı + mevcut aktiflik durumu
    SELECT
      is_active INTO current_state
    FROM estatemaster.customers
    WHERE id = p_id;

    -- Eğer kayıt yoksa
    IF current_state IS NULL THEN
      SET @oresult = 'NOT_FOUND';
      SELECT
        @oresult AS oresult;
      LEAVE main_block;
    END IF;

    -- Durum tersine çevrilir
    UPDATE estatemaster.customers
    SET is_active = NOT current_state,
        updated_at = NOW()
    WHERE id = p_id;

    -- Duruma göre çıktı döner
    SET @oresult = IF(NOT current_state, 'REACTIVATED', 'DEACTIVATED');
    SELECT
      @oresult AS oresult;
  END
  $$

--
-- Create procedure `sp_get_customer_by_id`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_customer_by_id (IN p_session_id char(36),
IN p_id char(36),
IN p_company_id char(36))
main_block:
  BEGIN
    DECLARE actualCompany char(36);
    DECLARE actualUser char(36);
    SET @oresult = '';
    SET @omessage = '';

    -- Oturum kontrolü ve bağlam yükleme
    CALL sp_load_session(p_session_id);
    SELECT
      @GlobalCompanyId INTO actualCompany;
    SELECT
      @GlobalUserId INTO actualUser;

    -- Tenant doğrulaması
    IF actualCompany != p_company_id THEN
      CALL sp_db_exception_msg('Tenant eşleşmesi başarısız.', 'UE-04');
      LEAVE main_block;
    END IF;

    -- Kayıt kontrolü
    IF NOT EXISTS (SELECT
          1
        FROM estatemaster.customers
        WHERE id = p_id
        AND company_id = p_company_id) THEN
      SET @oresult = 'NOT_FOUND';
      SET @omessage = 'Müşteri kaydı bulunamadı.';
      SELECT
        @oresult AS oresult,
        @omessage AS message;
      LEAVE main_block;
    END IF;

    -- Müşteri verisini getir
    SELECT
      id,
      customer_type,
      assigned_user_id,
      first_name,
      last_name,
      email,
      phone,
      birth_date,
      gender,
      budget_min,
      budget_max,
      preferred_province,
      preferred_district,
      preferred_neighborhood,
      preferred_square_meters,
      preferred_room_count,
      amenities,
      facade,
      source,
      last_interaction,
      notes,
      created_by,
      created_at,
      updated_at,
      updated_by,
      company_id
    FROM estatemaster.customers
    WHERE id = p_id
    AND company_id = p_company_id;
  END
  $$

--
-- Create procedure `sp_get_customers`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_customers ()
BEGIN
  SELECT
    id,
    first_name,
    last_name,
    email,
    phone,
    customer_type,
    budget_min,
    budget_max,
    preferred_province,
    preferred_district,
    preferred_neighborhood,
    preferred_square_meters,
    preferred_room_count,
    source,
    last_interaction,
    is_active,
    created_at

  FROM estatemaster.customers
  WHERE is_active = TRUE
  ORDER BY created_at DESC;
END
$$

--
-- Create procedure `sp_create_customer`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_customer (IN p_session_id char(36),
IN p_company_id char(36),
IN p_created_by char(36),
IN p_customer_type varchar(255),
IN p_assigned_user_id char(36),
IN p_first_name varchar(255),
IN p_last_name varchar(255),
IN p_email varchar(255),
IN p_phone varchar(25),
IN p_birth_date datetime,
IN p_gender varchar(10),
IN p_budget_min double,
IN p_budget_max double,
IN p_preferred_province varchar(255),
IN p_preferred_district varchar(255),
IN p_preferred_neighborhood varchar(255),
IN p_preferred_square_meters double,
IN p_preferred_room_count varchar(50),
IN p_amenities text,
IN p_facade varchar(100),
IN p_source varchar(100),
IN p_last_interaction datetime,
IN p_notes text)
main_block:
  BEGIN
    DECLARE intID char(36);
    DECLARE emailCount int DEFAULT 0;
    DECLARE companyId char(36);

    SET @oresult = '';
    SET @omessage = '';

    -- Oturum bilgilerini yükle
    CALL sp_load_session(p_session_id);
    SELECT
      @GlobalCompanyId INTO companyId;

    -- Aynı firma içinde e-posta zaten var mı?
    SELECT
      COUNT(*) INTO emailCount
    FROM estatemaster.customers
    WHERE email = p_email
    AND company_id = companyId;

    IF emailCount > 0 THEN
      SET @oresult = 'EMAIL_EXISTS';
      SET @omessage = CONCAT('Bu e-posta adresi zaten kayıtlı: ', p_email);
      SELECT
        @oresult AS oresult,
        @omessage AS message;
      LEAVE main_block;
    END IF;

    -- UUID oluştur, işlem başlat
    SET intID = UUID();
    START TRANSACTION;

      -- Müşteri kaydı
      INSERT INTO estatemaster.customers (id, created_at, created_by, company_id,
      customer_type, assigned_user_id,
      first_name, last_name, email, phone, birth_date,
      gender, budget_min, budget_max,
      preferred_province, preferred_district, preferred_neighborhood,
      preferred_square_meters, preferred_room_count,
      amenities, facade, source, last_interaction, notes)
        VALUES (intID, NOW(), p_created_by, companyId, p_customer_type, p_assigned_user_id, p_first_name, p_last_name, p_email, p_phone, p_birth_date, p_gender, p_budget_min, p_budget_max, p_preferred_province, p_preferred_district, p_preferred_neighborhood, p_preferred_square_meters, p_preferred_room_count, p_amenities, p_facade, p_source, p_last_interaction, p_notes);

      SET @oresult = intID;
      SET @omessage = 'Müşteri başarıyla oluşturuldu.';
      SELECT
        @oresult AS oresult,
        @omessage AS message;
    COMMIT;
  END
  $$

DELIMITER ;

--
-- Create table `_psmigrations`
--
CREATE TABLE _psmigrations (
  id int NOT NULL,
  name varchar(255) NOT NULL,
  executed_at datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `company_limits`
--
CREATE TABLE company_limits (
  company_id char(36) NOT NULL COMMENT 'Şirket UUID, companies.id ile bire bir eşleşir',
  max_user_count int DEFAULT 10 COMMENT 'Şirkete ait maksimum kullanıcı sayısı',
  contract_start_date date DEFAULT NULL COMMENT 'Sözleşmenin başlangıç tarihi',
  contract_end_date date DEFAULT NULL COMMENT 'Sözleşmenin bitiş tarihi',
  notes text DEFAULT NULL COMMENT 'Ek açıklamalar, özel tanımlar',
  created_at datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Kayıt oluşturulma tarihi',
  PRIMARY KEY (company_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Şirketlerin sözleşme bilgileri ve kullanıcı sınırlarını tutar',
ROW_FORMAT = DYNAMIC;

-- Table estatemaster._psmigrations does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
('34cd746e-35ab-11f0-9fb3-e40d36081ab9', '2025-05-20 21:49:49', '2025-08-30 02:55:49', 'knngksn', 'Deniz', 'Gökşen', '5449110054', 'Sakarya', 'admin', 'denizgoksen', '123', '2025-05-20 21:49:49', '123', 'knngksn@hotmail.com', ''),
('763553f7-35a6-11f0-9fb3-e40d36081ab9', '2025-05-20 21:15:51', '2025-05-20 21:15:51', 'cansugoksen', 'Kenan', 'Gökşen', '5449110054', 'Sakarya', 'modaretor', 'knngksn', '123', '2025-05-20 21:15:51', 'test2', 'knngksn@hotmail.com', ''),
('c78b7881-35aa-11f0-9fb3-e40d36081ab9', '2025-05-20 21:46:45', '2025-05-20 21:46:45', 'cansugoksen', 'Kenan', 'Gökşen', '5449110054', 'Bursa', 'admin', 'knngksn1', '123', '2025-05-20 21:46:45', '123', 'knngksn@hotmail.com', ''),
('ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2024-12-05 19:21:04', '2025-05-20 22:01:43', 'knngksn', 'Cansu', 'Gökşen Dğiştirildi', '5449110054', 'Sakarya', 'admin', 'cansugoksen', 'Kgksn.0507', '2024-12-05 19:21:04', 'Test', 'knngksn@hotmail.com', ''),
('f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-11-22 21:52:37', '2025-07-30 03:50:29', 'knngksn', 'Kenan', 'Gökşen', '0532 232 70 54', 'Sakarya', 'saleperson', 'knngksn', 'Kgksn.0507', '2024-11-22 21:52:37', 'Test Hesabı Silme...!!!!!!!!', 'knngksn@hotmail.com', 'b6f3a9e2-3c4d-4d8d-bc9b-01d56ae2321f');

-- 
-- Dumping data for table properties
--
INSERT INTO properties VALUES
('5098fccc-35ca-11f0-9fb3-e40d36081ab9', '2025-05-21 01:32:30', '2025-05-21 01:32:30', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asd', 'asd', 123, 'asd', 'asd', 123, 'asd', 'sale'),
('50da7176-35cb-11f0-9fb3-e40d36081ab9', '2025-05-21 01:39:39', '2025-05-21 01:39:39', 'knngksn', 'land', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'Satılı Arsa', '597 metre kare sapanca gölü manzaralı imarlı arsa', 500000, 'Sakarya', 'Serdivan', 597, 'Esentepe Mahallesi', 'sale'),
('6e3bd983-35cc-11f0-9fb3-e40d36081ab9', '2025-05-21 01:47:38', '2025-05-21 01:47:38', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asdasda', 'asdasd', 123123, 'asda', 'asdasd', 123123, 'asdasd', 'sale'),
('7e441ae8-35c9-11f0-9fb3-e40d36081ab9', '2025-05-21 01:26:37', '2025-05-21 01:26:37', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asd', 'asd', 123, 'asd', 'asd', 123, 'asd', 'sale'),
('a806ca04-35cc-11f0-9fb3-e40d36081ab9', '2025-05-21 01:49:15', '2025-05-21 01:49:15', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asdasd', 'asdas', 123, 'asdasd', 'asd', 123123, 'asdasd', 'sale'),
('c20ca0dd-38b3-11f0-9fb3-e40d36081ab9', '2025-05-24 18:28:35', '2025-05-24 18:28:35', 'knngksn', 'land', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'asd', 'asd', 123, 'İstanbul', 'asd', 123, 'asd', 'sale'),
('fb6d7cdf-37ab-11f0-9fb3-e40d36081ab9', '2025-05-23 11:00:24', '2025-05-23 11:00:24', 'knngksn', 'residential_propery', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', 'Modaldan ekleme', 'SAtılık 4+1 göl manzaralı ev', 15000000, 'Sakarya', 'Serdivan', 350, 'Esentepe', 'sale');

-- 
-- Dumping data for table login_sessions
--
INSERT INTO login_sessions VALUES
('000c4d36-6617-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 17:57:24', 0),
('032ee32f-66cc-11ef-b915-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-08-30 15:33:08', 0),
('060e1e42-a8ff-11ef-a0c7-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-22 21:24:34', 0),
('07bf2ca1-668d-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-22 02:47:15', 0),
('0b9ca9b4-64d7-11ef-b915-b025aa5ee41d', '', '', '2024-08-28 03:47:04', 0),
('0e05ca7b-3cdb-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-30 01:19:57', 0),
('108a2265-6cc5-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 00:43:29', 1),
('110b594b-6527-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:19:53', 0),
('11ab8876-6cef-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:44:09', 1),
('11dec8cd-3cdb-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-30 01:20:04', 0),
('1317ed10-68b1-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-24 20:10:18', 0),
('1afb7e6c-663d-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 22:30:10', 0),
('1f022aed-35ce-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 01:59:44', 0),
('22c3da0c-6ad5-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:33:29', 1),
('239ae45b-6cef-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:44:39', 1),
('2661ea3f-64de-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:37:56', 0),
('2770e31d-35ce-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 01:59:58', 0),
('27850206-68f5-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-25 04:17:38', 0),
('27f9902f-6520-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:30:25', 0),
('2b52c208-35cf-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 02:07:14', 0),
('2ccf9536-64da-11ef-b915-b025aa5ee41d', '', '2', '2024-08-28 04:09:28', 0),
('2dff0b5f-64d2-11ef-b915-b025aa5ee41d', '', '', '2024-08-28 03:12:14', 0),
('2fc9084d-675f-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-23 03:51:36', 0),
('31cd0b6d-663d-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 22:30:48', 0),
('3469267b-6744-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-23 00:38:28', 0),
('35350cf9-6ad5-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:34:00', 1),
('385e50f3-6527-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:20:59', 0),
('3a3ae375-68f1-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-25 03:49:32', 0),
('3d95ccf8-6ad6-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:41:23', 1),
('3e310b80-b324-11ef-81a0-b025aa5ee41d', '', '37f720ba-b324-11ef-81a0-b025aa5ee41d', '2024-12-05 19:16:11', 0),
('3ebd44c3-68e2-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-25 02:02:17', 0),
('3ec0127b-654e-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 18:00:20', 0),
('407b8fea-6551-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 18:21:52', 0),
('414eb5d9-6552-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 18:29:02', 0),
('43103e66-6cfe-11f0-8e78-e40d36081ab9', 'b6f3a9e2-3c4d-4d8d-bc9b-01d56ae2321f', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 07:32:55', 1),
('4708af03-675e-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-23 03:45:06', 0),
('473966ef-3cd3-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-30 00:24:17', 0),
('48278e89-3c9f-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-29 18:12:05', 0),
('4a0cde19-6ad3-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:20:16', 1),
('4abf40a5-6ad3-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:20:17', 1),
('4ac945c3-094a-11f0-bbc1-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-25 10:25:13', 0),
('4ae4c1b2-6ad3-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:20:17', 1),
('4b546c03-9326-11ef-b11d-e40d36081ab9', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-10-26 02:10:15', 0),
('4b8ac796-093d-11f0-bbc1-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-03-25 08:52:11', 0),
('4c5bac0d-652a-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:43:01', 0),
('4f526ac4-6ad3-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:20:24', 1),
('4faf3120-6ad3-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:20:25', 1),
('4fc67bc4-6ad3-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:20:25', 1),
('4fe058a7-6ad3-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:20:25', 1),
('4fe94416-093d-11f0-bbc1-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-03-25 08:52:18', 0),
('5039180f-6acf-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 12:51:48', 0),
('505da356-64dc-11ef-b915-b025aa5ee41d', '', '', '2024-08-28 04:24:47', 0),
('50b3093b-6554-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 18:43:47', 0),
('50b32654-3cb5-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-29 20:49:48', 0),
('5109ca39-35a3-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-20 20:53:20', 0),
('51d7ad16-6cdf-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 03:51:25', 1),
('520ca422-6521-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:38:45', 0),
('5703f934-093d-11f0-bbc1-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-03-25 08:52:30', 0),
('583b9c00-a902-11ef-a0c7-b025aa5ee41d', '', '56cc975d-a902-11ef-a0c7-b025aa5ee41d', '2024-11-22 21:48:20', 0),
('59ac18f9-bb1c-11ef-9846-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-15 22:39:50', 0),
('5ae16704-6619-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-29 18:14:15', 0),
('5c8f73a0-6547-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:11:04', 0),
('67589cf5-6522-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:46:30', 0),
('6776ab4d-655c-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:41:41', 0),
('68058046-3cba-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-29 21:26:15', 0),
('6ba5d91b-6552-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 18:30:13', 0),
('6d1b588e-64de-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:39:54', 0),
('7265720a-66c0-11ef-b915-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-08-30 14:10:21', 0),
('73af1be9-70fa-11ef-b915-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-09-12 14:30:45', 0),
('742c32e7-6ce9-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:03:58', 1),
('75c41630-6ce9-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:04:00', 1),
('763d122a-6ce9-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:04:01', 1),
('7653736e-6ce9-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:04:01', 1),
('766bc8f2-6ce9-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:04:01', 1),
('76859479-6ce9-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:04:02', 1),
('76ea982b-35cd-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 01:55:02', 0),
('78999b18-6551-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 18:23:26', 0),
('7d652709-3ca5-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-29 18:56:31', 0),
('7d840da2-35a4-11f0-9fb3-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-05-20 21:01:44', 0),
('7d883d5b-6526-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:15:46', 0),
('7f6c5c6d-663f-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 22:47:17', 0),
('810a6fb5-64d9-11ef-b915-b025aa5ee41d', '', '', '2024-08-28 04:04:40', 0),
('81a52997-6cef-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:47:17', 1),
('83b6e03a-6ce9-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:04:24', 1),
('86789406-38d8-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-24 22:51:46', 0),
('89c36a3f-64dd-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:33:33', 0),
('8b9da01c-6547-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:12:23', 0),
('8c679ad5-64e0-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:55:06', 0),
('8e2d4ed1-2d97-11f0-9159-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-05-10 15:08:59', 0),
('8f2c4f99-6ad4-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:29:21', 1),
('9024cfaa-64db-11ef-b915-b025aa5ee41d', '', '', '2024-08-28 04:19:25', 0),
('9235b1b5-68f0-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-25 03:44:50', 0),
('92819a0c-6cef-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:47:45', 1),
('96972082-6558-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:14:22', 0),
('9945d0a3-b324-11ef-81a0-b025aa5ee41d', '', '92aab838-b324-11ef-81a0-b025aa5ee41d', '2024-12-05 19:18:44', 0),
('99577ea4-6547-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:12:46', 0),
('9a135df8-6619-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-29 18:16:01', 0),
('9c8c78aa-665d-11ef-b915-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-08-30 02:22:51', 0),
('9e373d7e-6558-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:14:35', 0),
('a0253179-6520-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:33:47', 0),
('a42db2f7-8533-11f0-9d5d-e40d36081ab9', 'b6f3a9e2-3c4d-4d8d-bc9b-01d56ae2321f', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-08-30 02:55:29', 1),
('a486c668-665d-11ef-b915-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-08-30 02:23:05', 0),
('a73caa70-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:20', 1),
('a7b40c22-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:21', 1),
('a7cdec98-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:21', 1),
('a7e224b3-6529-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:38:25', 0),
('a7e4ae67-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:21', 1),
('a7fdee8e-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:21', 1),
('a8145b7d-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:22', 1),
('a82b7b54-6558-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:14:52', 0),
('a8452713-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:22', 1),
('a85c81b2-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:22', 1),
('a8748050-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:22', 1),
('a88c479f-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:22', 1),
('a8be23a2-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:23', 1),
('a8e3e75c-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:23', 1),
('a90d2ffb-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:23', 1),
('a928189a-0939-11f0-bbc1-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-25 08:26:10', 0),
('a92c4f43-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:23', 1),
('a946b593-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:24', 1),
('a96ebf93-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:24', 1),
('a9a23818-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:24', 1),
('a9dd02ff-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:25', 1),
('a9f2ba70-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:25', 1),
('aa0ac46c-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:25', 1),
('aa3e495f-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:25', 1),
('aa7227cd-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:26', 1),
('aa8a913b-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:26', 1),
('aaa244d1-6cef-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-30 05:48:26', 1),
('ae71e4e9-6ad4-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:30:14', 1),
('af5450cf-6cef-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:48:34', 1),
('af58b3a0-35cd-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 01:56:37', 0),
('b135137f-3cc4-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-29 22:39:53', 0),
('b18f163b-68ea-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-25 03:02:45', 0),
('b45768ad-67c5-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-23 16:05:28', 0),
('b5a369b5-6558-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:15:15', 0),
('b5fd87bd-093b-11f0-bbc1-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-03-25 08:40:50', 0),
('b923b93c-bde4-11ef-9846-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-19 11:39:12', 0),
('b957be8b-6ad4-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:30:32', 1),
('b9bd7564-a8fe-11ef-a0c7-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-22 21:22:26', 0),
('ba10d0da-b46c-11ef-81a0-b025aa5ee41d', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-07 10:27:34', 0),
('be298d24-094f-11f0-bbc1-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-25 11:04:14', 0),
('c16f1594-35ac-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-20 22:00:54', 0),
('c1fb46b5-a8fc-11ef-a0c7-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-22 21:08:21', 0),
('c53a8aa4-05a6-11f0-bbc1-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-20 19:17:08', 0),
('c561320e-6556-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:01:22', 0),
('c7eac9be-b323-11ef-81a0-b025aa5ee41d', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-05 19:12:53', 0),
('cad7700b-654a-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:35:37', 0),
('cd32eeba-3749-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-22 23:17:36', 0),
('ce1f89c0-68d9-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-25 01:01:52', 0),
('cf4e03cb-05a9-11f0-bbc1-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-20 19:38:53', 0),
('d0fc46a9-651f-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 12:27:59', 0),
('d15718a7-2d03-11f0-9159-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-09 21:31:26', 0),
('d36743f3-094e-11f0-bbc1-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-25 10:57:40', 0),
('d6a6970f-6547-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:14:29', 0),
('d746c703-b324-11ef-81a0-b025aa5ee41d', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-05 19:20:28', 0),
('da823d5c-b324-11ef-81a0-b025aa5ee41d', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-12-05 19:20:33', 0),
('e0c4965f-6547-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 17:14:45', 0),
('e57c6564-6558-11ef-b915-b025aa5ee41d', '', '4c9a997f-6552-11ef-b915-b025aa5ee41d', '2024-08-28 19:16:35', 0),
('e5f5a9ce-64db-11ef-b915-b025aa5ee41d', '', '', '2024-08-28 04:21:49', 0),
('e8fbc85a-64dd-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 04:36:13', 0),
('ea4b4527-a8fc-11ef-a0c7-b025aa5ee41d', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-22 21:09:28', 0),
('ea66b1b6-6ce0-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 04:02:50', 1),
('ea9c74af-68ee-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-25 03:32:59', 0),
('eaa4def3-9b93-11ef-b12d-e40d36081ab9', '', 'e888f723-6643-11ef-b915-b025aa5ee41d', '2024-11-05 19:35:07', 0),
('edbffee1-675d-11f0-8e78-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-07-23 03:42:36', 0),
('ee208c9d-0dad-11f0-bbc1-e40d36081ab9', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2025-03-31 00:28:32', 0),
('ee6f7e72-67c3-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-23 15:52:46', 0),
('f06e7e32-b324-11ef-81a0-b025aa5ee41d', '', 'ec856b8c-b324-11ef-81a0-b025aa5ee41d', '2024-12-05 19:21:10', 0),
('f1472438-6ce8-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-30 05:00:18', 1),
('f2a77b7d-6995-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-25 23:28:39', 0),
('f5c23789-64dc-11ef-b915-b025aa5ee41d', '', '6b5a2e0f-9c7a-4a1b-8e5d-3e8a1f9b5d6c', '2024-08-28 04:29:25', 0),
('f67827ea-6528-11ef-b915-b025aa5ee41d', '', 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6', '2024-08-28 13:33:27', 0),
('f6b65ff7-a902-11ef-a0c7-b025aa5ee41d', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2024-11-22 21:52:46', 0),
('fa903854-35ce-11f0-9fb3-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-21 02:05:53', 0),
('fade5e45-3cc1-11f0-b3ef-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-05-29 22:20:28', 0),
('fe81005c-6ad4-11f0-8e78-e40d36081ab9', '', 'f164ce7d-a902-11ef-a0c7-b025aa5ee41d', '2025-07-27 13:32:28', 1);

-- 
-- Dumping data for table db_exception_msg
--
INSERT INTO db_exception_msg VALUES
(1, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:57:05'),
(2, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:57:05'),
(3, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:57:30'),
(4, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:57:30'),
(5, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:58:01'),
(6, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:58:01'),
(7, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:58:07'),
(8, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:58:07'),
(9, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:58:47'),
(10, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 03:58:47'),
(11, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 05:48:30'),
(12, NULL, NULL, 'DB_EXCEPTION', NULL, 'ERROR', '2025-07-30 05:48:30'),
(13, 'af5450cf-6cef-11f0-8e78-e40d36081ab9', '', 'Sistem Hatası: oturum bulunamadı.', 'AUTH-02', 'ERROR', '2025-07-30 06:27:32'),
(14, 'af5450cf-6cef-11f0-8e78-e40d36081ab9', '', 'Sistem Hatası: oturum bulunamadı.', 'AUTH-02', 'ERROR', '2025-07-30 06:29:34'),
(15, 'af5450cf-6cef-11f0-8e78-e40d36081ab9', '', 'Sistem Hatası: oturum bulunamadı.', 'AUTH-02', 'ERROR', '2025-07-30 06:31:18'),
(16, 'af5450cf-6cef-11f0-8e78-e40d36081ab9', '', 'Sistem Hatası: oturum bulunamadı.', 'AUTH-02', 'ERROR', '2025-07-30 07:12:44'),
(17, 'af5450cf-6cef-11f0-8e78-e40d36081ab9', '', 'Sistem Hatası: oturum bulunamadı.', 'AUTH-02', 'ERROR', '2025-07-30 07:13:13'),
(18, 'af5450cf-6cef-11f0-8e78-e40d36081ab9', '', 'Sistem Hatası: oturum bulunamadı.', 'AUTH-02', 'ERROR', '2025-07-30 07:22:05');

-- 
-- Dumping data for table customers
--
INSERT INTO customers VALUES
('6e112c5a-6cfe-11f0-8e78-e40d36081ab9', 'b6f3a9e2-3c4d-4d8d-bc9b-01d56ae2321f', '2025-07-30 07:34:07', NULL, 'knngksn', 'Potansiyel', 'de8f59c4-9a6a-4900-b7b0-cb4db7f92951', 'Ahmet', 'Yıldı', 'kenan', '(542) 548 72 54', '1996-12-15', 'Male', 152, 175, 'sad', 'asd', 'asd', 15, '15', 'ad', 'asd', 'asd', '2025-05-12 12:21:00', 'asd', 1, NULL),
('71a9d7aa-6cfb-11f0-8e78-e40d36081ab9', '', '2025-07-30 07:12:44', NULL, 'knngksn', 'Potansiyel', 'de8f59c4-9a6a-4900-b7b0-cb4db7f92951', 'Ahmet', 'yıldı', 'canssucirakgolu@gmail.com', '(542) 548 72 54', '2025-07-30', 'Female', 123123, 12312312, 'asd', 'asd', 'asd', 123, '3', 'asd', 'asd', 'asd', '2025-07-11 07:12:00', 'asd', 1, NULL),
('7507e476-67d8-11f0-8e78-e40d36081ab9', '', '2025-07-23 18:19:42', '2025-07-27 01:54:22', 'knngksn', 'Potansiyel', '7d3e7c20-709c-4895-996d-2b9331ae4663', 'Deniz', 'Gökşen', 'denizgoksen@gmail.com', '(544) 911 00 54', '2025-01-03', 'Male', 500000, 1000000, 'Sakarya', 'Serdivan', 'İstiklal', 250, '6+1', 'havuz', 'Güney', 'Telefon', '2025-07-25 18:19:00', 'Kaymaklıı', 1, 'knngksn'),
('82c872dc-6cfb-11f0-8e78-e40d36081ab9', '', '2025-07-30 07:13:13', NULL, 'knngksn', 'Potansiyel', 'de8f59c4-9a6a-4900-b7b0-cb4db7f92951', 'Ahmet', 'yıldı', 'canssucirakgaaolu@gmail.com', '(542) 548 72 54', '2025-07-30', 'Female', 123123, 12312312, 'asd', 'asd', 'asd', 123, '3', 'asd', 'asd', 'asd', '2025-07-11 07:12:00', 'asd', 1, NULL),
('8776d91f-6760-11f0-8e78-e40d36081ab9', '', '2025-07-23 04:01:13', '2025-07-25 04:18:33', 'test_seed', 'Eski', '7d3e7c20-709c-4895-996d-2b9331ae4663', 'Ayşe', 'Yıldız', 'ayse.yildiz@example.com', '05551112233', '0101-01-01', 'Male', 500000, 1500000, 'Ankara', 'Çankaya', 'Ayrancı', 132, '6+1', '', '', '', '2025-07-25 04:18:00', '', 1, 'knngksn'),
('c009f889-6cfc-11f0-8e78-e40d36081ab9', '', '2025-07-30 07:22:05', NULL, 'knngksn', 'Potansiyel', '7d3e7c20-709c-4895-996d-2b9331ae4663', 'Test deneme', 'deneme', 'deneme', '(542) 548 72 54', '2025-07-07', 'Male', 123123, 12312321, 'deneme', 'deneme', 'deneme', 123, '3', 'deneme', 'deneme', 'deneme', '2025-07-29 07:22:00', 'deneme', 1, NULL),
('c09ccdc9-6996-11f0-8e78-e40d36081ab9', '', '2025-07-25 23:34:24', NULL, 'knngksn', 'Aktif', '7d3e7c20-709c-4895-996d-2b9331ae4663', 'Ahmet', 'Yılmaz', 'ahmetyılmaz@hotmail.com', '(549) 526 12 48', '1976-08-15', 'Male', 2000000, 2500000, 'Ankara', 'Keçiören', '7.cadde', 225, '5+1', 'Havuz, kapalı havuz, kapalı otopark', 'kuzey', 'Website', '2025-07-25 23:34:00', 'Yeni bir ev bakıyor', 1, NULL),
('c66c1c05-6cfe-11f0-8e78-e40d36081ab9', 'b6f3a9e2-3c4d-4d8d-bc9b-01d56ae2321f', '2025-07-30 07:36:35', NULL, 'knngksn', 'Potansiyel', 'de8f59c4-9a6a-4900-b7b0-cb4db7f92951', 'Ahmet', 'Yıldı', 'kenana', '(542) 548 72 54', '1996-12-15', 'Male', 152, 175, 'sad', 'asd', 'asd', 15, '15', 'ad', 'asd', 'asd', '2025-05-12 12:21:00', 'asd', 1, NULL),
('da2e16cd-67d7-11f0-8e78-e40d36081ab9', '', '2025-07-23 18:15:22', '2025-07-25 04:02:36', 'knngksn', 'Potansiyel', 'de8f59c4-9a6a-4900-b7b0-cb4db7f92951', 'Cansu', 'Gökşen', 'canssucirakoglu@gmail.com', '(542) 548 72 54', '1996-12-29', 'Female', 1000000, 1500000, 'Sakarya', 'Serdivan', 'İstiklal', 150, '4+1', 'havuz, kapalı otopark', 'kuzey', '', '2025-07-25 00:21:00', 'Yüksek potansiyel', 1, 'knngksn');

-- Table estatemaster.company_limits does not contain any data (it is empty)

-- 
-- Dumping data for table companies
--
INSERT INTO companies VALUES
('b6f3a9e2-3c4d-4d8d-bc9b-01d56ae2321f', 'EMTRIAL001', 'EstateMaster Teknoloji A.Ş.', 'iletisim@estatemaster.com', 'estatemaster.com', 1, '2025-07-30 04:58:14');

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;